//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMBIENTE_CHAVE
    {
        public int AMCH_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int AMBI_CD_ID { get; set; }
        public System.DateTime AMCH_DT_ENTREGA { get; set; }
        public System.DateTime AMCH_DT_PREVISTA { get; set; }
        public Nullable<System.DateTime> AMCH_DT_DEVOLUCAO { get; set; }
        public string AMCH_DS_JUSTIFICATIVA { get; set; }
        public string AMCH_TX_OBSERVACOES { get; set; }
        public int AMCH_IN_ATIVO { get; set; }
    
        public virtual AMBIENTE AMBIENTE { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
