//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORIZACAO_ACESSO_ANEXO
    {
        public int AAAN_CD_ID { get; set; }
        public int AUAC_CD_ID { get; set; }
        public string AAAN_NM_TITULO { get; set; }
        public System.DateTime AAAN_DT_ANEXO { get; set; }
        public int AAAN_IN_TIPO { get; set; }
        public string AAAN_AQ_ARQUIVO { get; set; }
        public Nullable<int> AAAN_IN_ATIVO { get; set; }
    
        public virtual AUTORIZACAO_ACESSO AUTORIZACAO_ACESSO { get; set; }
    }
}
