//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLE_VEICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTROLE_VEICULO()
        {
            this.CONTROLE_VEICULO_ACOMPANHAMENTO = new HashSet<CONTROLE_VEICULO_ACOMPANHAMENTO>();
        }
    
        public int COVE_CD_ID { get; set; }
        public Nullable<int> TIVE_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> COVE_DT_ENTRADA { get; set; }
        public Nullable<System.DateTime> COVE_DT_SAIDA { get; set; }
        public string COVE_NM_PLACA { get; set; }
        public string COVE_NM_MARCA { get; set; }
        public string COVE_DS_DESCRICAO { get; set; }
        public int COVE_IN_ATIVO { get; set; }
        public string COVE_NM_MODELO { get; set; }
        public string COVE_NM_COR { get; set; }
        public Nullable<System.DateTime> COVE_DT_PREVISAO_SAIDA { get; set; }
        public string COVE_DS_JUSTIFICATIVA { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual TIPO_VEICULO TIPO_VEICULO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROLE_VEICULO_ACOMPANHAMENTO> CONTROLE_VEICULO_ACOMPANHAMENTO { get; set; }
    }
}
