//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLE_VEICULO_ACOMPANHAMENTO
    {
        public int CVAC_CD_ID { get; set; }
        public int COVE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> CVAC_DT_ACOMPANHAMENTO { get; set; }
        public string CVAC_DS_TEXTO { get; set; }
        public Nullable<int> CVAC_IN_ATIVO { get; set; }
    
        public virtual CONTROLE_VEICULO CONTROLE_VEICULO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
