//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCOMENDA_COMENTARIO
    {
        public int ECOM_CD_ID { get; set; }
        public Nullable<int> ENCO_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> ECOM_DT_COMENTARIO { get; set; }
        public string ECOM_DS_COMENTARIO { get; set; }
        public Nullable<int> ECOM_IN_ATIVO { get; set; }
    
        public virtual ENCOMENDA ENCOMENDA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
