//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADA_SAIDA_COMENTARIO
    {
        public int ESCO_CD_ID { get; set; }
        public int ENSA_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> ESCO_DT_COMENTARIO { get; set; }
        public string ESCO_DS_COMENTARIO { get; set; }
        public Nullable<int> ESCO_IN_ATIVO { get; set; }
    
        public virtual ENTRADA_SAIDA ENTRADA_SAIDA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
