//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_CONVIDADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTA_CONVIDADO()
        {
            this.CONVIDADO = new HashSet<CONVIDADO>();
        }
    
        public int LICO_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> RESE_CD_ID { get; set; }
        public string LICO_NM_LISTA { get; set; }
        public System.DateTime LICO_DT_EVENTO { get; set; }
        public System.DateTime LICO_DT_CADASTRO { get; set; }
        public int LICO_IN_ATIVO { get; set; }
        public string LICO_TX_OBSERVACOES { get; set; }
        public string LICO_NM_CONVIDADO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONVIDADO> CONVIDADO { get; set; }
        public virtual RESERVA RESERVA { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
