//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_CONVIDADO_COMENTARIO
    {
        public int LCCM_CD_ID { get; set; }
        public int LICO_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime LCCM_DT_COMENTARIO { get; set; }
        public string LCCM_DS_COMENTARIO { get; set; }
        public int LCCM_IN_ATIVO { get; set; }
    
        public virtual LISTA_CONVIDADO LISTA_CONVIDADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
