//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_CONVIDADO_ANEXO
    {
        public int LCAN_CD_ID { get; set; }
        public int LICO_CD_ID { get; set; }
        public Nullable<System.DateTime> LCAN_DT_ANEXO { get; set; }
        public string LCAN_NM_TITULO { get; set; }
        public Nullable<int> LCAN_IN_TIPO { get; set; }
        public string LCAN_AQ_ARQUIVO { get; set; }
        public Nullable<int> LCAN_IN_ATIVO { get; set; }
    
        public virtual LISTA_CONVIDADO LISTA_CONVIDADO { get; set; }
    }
}
