//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA_ANEXO
    {
        public int REAN_CD_ID { get; set; }
        public int RESE_CD_ID { get; set; }
        public string REAN_NM_TITULO { get; set; }
        public Nullable<System.DateTime> REAN_DT_ANEXO { get; set; }
        public Nullable<int> REAN_IN_TIPO { get; set; }
        public string REAN_AQ_ARQUIVO { get; set; }
        public Nullable<int> REAN_IN_ATIVO { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
    }
}
