//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_AGENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_AGENDA()
        {
            this.AGENDA_CONDOMINIO = new HashSet<AGENDA_CONDOMINIO>();
        }
    
        public int TIAG_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string TIAG_NM_NOME { get; set; }
        public int TIAG_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDA_CONDOMINIO> AGENDA_CONDOMINIO { get; set; }
    }
}
