//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADE_ANEXO
    {
        public int UNAN_CD_ID { get; set; }
        public int UNID_CD_ID { get; set; }
        public string UNAN_NM_TITULO { get; set; }
        public System.DateTime UNAN_DT_ANEXO { get; set; }
        public int UNAN_IN_TIPO { get; set; }
        public string UNAN_AQ_ARQUIVO { get; set; }
        public int UNAN_IN_ATIVO { get; set; }
    
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
