//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_ESCALA_TRABALHO
    {
        public int USET_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<System.DateTime> USET_DT_DATA { get; set; }
        public string USET_HR_INICIO { get; set; }
        public string USET_HR_FINAL { get; set; }
        public string USET_HR_ALMOCO_INICIO { get; set; }
        public string USET_HR_ALMOCO_FINAL { get; set; }
        public Nullable<int> USET_IN_ATIVO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
