//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_CONTROLE_ENTRADA
    {
        public int USCE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime USCE_DT_MARCACAO { get; set; }
        public int USCE_IN_DIRECAO { get; set; }
        public int USCE_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> USCE_HR_ENTRADA { get; set; }
        public Nullable<System.DateTime> USCE_HR_SAIDA_ALMOCO { get; set; }
        public Nullable<System.DateTime> USCE_HR_VOLTA_ALMOCO { get; set; }
        public Nullable<System.DateTime> USCE_HR_SAIDA { get; set; }
        public Nullable<int> USCE_IN_VALIDADO { get; set; }
        public string USCE_DS_JUSTIFICATIVA { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
